# student mark analyzer


In [1]:
import numpy as np

In [2]:
marks = np.array([67, 89, 45, 90, 76, 55, 32])

In [3]:
print("students marks")

students marks


In [4]:
print(marks)

[67 89 45 90 76 55 32]


In [6]:
print("average marks:", marks.mean())

average marks: 64.85714285714286


In [7]:
print("highes marks:", marks.max())

highes marks: 90


In [8]:
print("lower marks:", marks.min())

lower marks: 32


In [10]:
passed = marks[marks >= 50]

In [11]:
print("passed students marks:")

passed students marks:


In [12]:
print(passed)

[67 89 90 76 55]


In [13]:
failed = marks[marks <= 50]


In [16]:
print("failed student marks:")

failed student marks:


In [17]:
print(failed)

[45 32]


In [18]:
percentage = (marks/100)*100

In [19]:
print("percentages:")

percentages:


In [20]:
print(percentage)

[67. 89. 45. 90. 76. 55. 32.]


In [21]:
for i in marks:
    if i >= 90:
        print("grade A")
    if i >= 75:
        print("grade B")
    if i >= 50:
        print("grade C")
    else:
        print("fail")

grade C
grade B
grade C
fail
grade A
grade B
grade C
grade B
grade C
grade C
fail


In [26]:
marks = [67, 89, 45, 90, 76, 55, 32]
pass_count = 0
fail_count = 0
for i in marks:
    if i >= 50:
        print("pass")
        pass_count += 1
    else:
        print("fail")
        fail_count += 1
print("passed students:", pass_count)
print("failed studets:", fail_count)

pass
pass
fail
pass
pass
pass
fail
passed students: 5
failed studets: 2
